// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Data;
using Server.Models.Game;
using Server.Models.Game.Timeline;
using Server.Models.Music;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129200002_AddGameOverReasonToSession")]
    partial class AddGameOverReasonToSession
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Server.Models.Game.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaseGameSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("JoinOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlayerType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<List<TimelineCard>>("Timeline")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Tokens")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaseGameSessionId");

                    b.HasIndex("JoinOrder");

                    b.ToTable("Players");

                    b.HasDiscriminator<string>("PlayerType").HasValue("Standard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Server.Models.Game.Sessions.BaseGameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<MatchConfiguration>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Song>("CurrentActiveSong")
                        .HasColumnType("jsonb");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<string>("GameOverReason")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string>("PlayedSongIds")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RoomCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoomCode")
                        .HasDatabaseName("IX_GameSessions_RoomCode");

                    b.ToTable("GameSessions");

                    b.HasDiscriminator<string>("SessionType").HasValue("BaseGameSession");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Server.Models.Music.Song", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviewUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("SpotifyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Language")
                        .HasDatabaseName("IX_Songs_Language");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Server.Models.Game.Players.OnlinePlayer", b =>
                {
                    b.HasBaseType("Server.Models.Game.Players.Player");

                    b.Property<string>("ConnectionId")
                        .HasColumnType("text");

                    b.Property<bool>("IsConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("Online");
                });

            modelBuilder.Entity("Server.Models.Game.Sessions.ExternalPlaylistSession", b =>
                {
                    b.HasBaseType("Server.Models.Game.Sessions.BaseGameSession");

                    b.Property<string>("ExternalPlaylistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("External");
                });

            modelBuilder.Entity("Server.Models.Game.Sessions.LocalDatabaseSession", b =>
                {
                    b.HasBaseType("Server.Models.Game.Sessions.BaseGameSession");

                    b.HasDiscriminator().HasValue("Local");
                });

            modelBuilder.Entity("Server.Models.Game.Players.Player", b =>
                {
                    b.HasOne("Server.Models.Game.Sessions.BaseGameSession", null)
                        .WithMany("Players")
                        .HasForeignKey("BaseGameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Models.Game.Sessions.BaseGameSession", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
